### ISSUE TITLE
cannot install teaful-devtool

### ISSUE THREAD

**Issue by WreewanMorhee** [teafuljs/teaful-devtools#4]
node version: 15.14.0

app enviroment: create react app 

react-scripts version: 4.0.1

how to install: npm i teaful-devtools

error information: 

<img width="571" alt="Screen Shot 2021-12-18 at 3 03 12 AM" src="https://user-images.githubusercontent.com/33398071/146595029-a198c74b-3fc2-49e3-ad32-0a98f2ffab04.png">

**Comment by aralroca** [comment]
You need at least teaful 0.9. For versions prior to 0.9 it does not work, this is normal.

![image](https://user-images.githubusercontent.com/13313058/146596786-9c05423b-7044-4d89-815b-0210545c72c2.png)

**Comment by WreewanMorhee** [comment]
resolved

thank u !
