### ISSUE TITLE
Dev-Tool not finding Stores

### ISSUE THREAD

**Issue by barneyparker** [teafuljs/teaful-devtools#8]
Package Versions:
- Teaful 0.10.0
- Teaful-devtools 0.5.1

OS: MacOS 11.5.2
NodeJS: 14.7.4
Npm: 6.14.14

What Happened:
Teaful Devtools panel shows:
```
No Teaful store has been found. [Retry]
```

What was expected:
Stores to be visible in the planel

I would love to submit a pull request, but I am not sure how to debug the issue :(

Additional Details:

The app is a standard create-react-app.  In the entrypoint index.js I have:
```js
/* eslint-disable import/first */
if (process.env.NODE_ENV==='development') {
  require("teaful-devtools");
}
```

I define the stores in some external files.  They're basic and follow notes from the Teaful docs:
```js
import createStore from "teaful"

function onAfterUpdate({ store, prevStore }) {
  console.log("Accounts Store Update")
}

export const { useStore: useAccounts } = createStore([], onAfterUpdate)
```

And then wherever I need to access one of the stores I have

```js
import { useAccounts } from '../Lib/storeAccounts'
.
.
.
export default function Accounts() {
  const [accounts] = useAccounts()
```

I believe i'm doing it right, but i'm not normally a react dev and so may be missing something vital/obvious 😆 

Any help here would be appreciated

**Comment by aralroca** [comment]
Ensure your `teaful-devtools` import is at the top, before the imports of your application (components, store, etc).

**Comment by barneyparker** [comment]
@aralroca that `require` is at the very top of the index.js file

**Comment by aralroca** [comment]
Looks an issue with `require`. Reeplacing to `import 'teaful-devtools'` works fine:

![image](https://user-images.githubusercontent.com/13313058/165803702-7203f36c-0b6a-4228-a586-b4113b9b4a87.png)

It seems that when compiling it moves the imports above the `require` and that's why it doesn't detect it.

Thank you for reporting the issue. Let's see if we can find a solution to strip `teaful-devtools` in production using create-react-app.

**Comment by barneyparker** [comment]
Oh wow, that never occurred to me!  I will give it a try to confirm.  Thanks for the amazingly fast response 👍

**Comment by barneyparker** [comment]
Hi @aralroca Just a quick message to confirm that your fix worked perfectly 👍

**Comment by aralroca** [comment]
With `import 'teaful-devtools'` you get it in both development and production. To remove `teaful-devtools` from production (if desired), it is certainly possible to do so with webpack's [resolve.alias](https://webpack.js.org/configuration/resolve/). It will be a little more complex than the way that you had put with the require.
